// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKwHSzjNzrFkRO8iiYRhNUvz0VBYwb_SM',
    appId: '1:996151554218:web:42f803b979dfe6413c20d3',
    messagingSenderId: '996151554218',
    projectId: 'instagram-clone-741f4',
    authDomain: 'instagram-clone-741f4.firebaseapp.com',
    storageBucket: 'instagram-clone-741f4.appspot.com',
    measurementId: 'G-MR6LPB8EDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3P41ccJPzuq6weYWpb9bo7mSCPUEuju8',
    appId: '1:996151554218:android:275feb1aad0224af3c20d3',
    messagingSenderId: '996151554218',
    projectId: 'instagram-clone-741f4',
    storageBucket: 'instagram-clone-741f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJHwN7-3GDAfm_ywr-c1Dl2o-XexNx09w',
    appId: '1:996151554218:ios:81777770a36ff7b63c20d3',
    messagingSenderId: '996151554218',
    projectId: 'instagram-clone-741f4',
    storageBucket: 'instagram-clone-741f4.appspot.com',
    iosClientId: '996151554218-emkschnlufqb5vk9uc5g3l57glke1v56.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJHwN7-3GDAfm_ywr-c1Dl2o-XexNx09w',
    appId: '1:996151554218:ios:81777770a36ff7b63c20d3',
    messagingSenderId: '996151554218',
    projectId: 'instagram-clone-741f4',
    storageBucket: 'instagram-clone-741f4.appspot.com',
    iosClientId: '996151554218-emkschnlufqb5vk9uc5g3l57glke1v56.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );
}
